---
title: "Johns Hopkins COVID 19 Report"
author: "Kurtis Pritchard"
date: "2024-08-10"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load Libraries

```{r}
library(tidyverse)
library(conflicted)
library(lubridate)
library(caret)
library(xgboost)
library(pROC)
library(PRROC)
library(MLmetrics)
library(glmnet)
library(car)
library(smotefamily)
library(ROSE)
```

# Read Datasets

```{r import_data}
url <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv"
us_cases <- read_csv(url)

url <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv"
global_cases <- read_csv(url)

url <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv"
us_deaths <- read_csv(url)

url <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv"
global_deaths <- read_csv(url)
```

# Inspect Data

```{r}
head(us_cases)
```

```{r}
head(us_deaths)
```

```{r}
head(global_cases)
```

```{r}
head(global_deaths)
```

# pivot data

```{r}
# pivot us cases
us_cases <- us_cases %>%
  pivot_longer(cols = -c(UID, iso2, iso3, code3, FIPS, Admin2, Province_State, Country_Region, Lat, Long_, Combined_Key), names_to = "date", values_to = "cases") %>%
  select(-c(UID, iso2, iso3, code3, FIPS, Lat, Long_, Combined_Key))
us_cases
```

```{r}
# pivot us deaths
us_deaths <- us_deaths %>%
  pivot_longer(cols = -c(UID, iso2, iso3, code3, FIPS, Admin2, Province_State, Country_Region, Lat, Long_, Combined_Key, Population), names_to = "date", values_to = "deaths") %>%
  select(-c(UID, iso2, iso3, code3, FIPS, Lat, Long_))
us_deaths
```

```{r}
# pivot global cases
global_cases <- global_cases %>%
  pivot_longer(cols = -c("Province/State", "Country/Region", "Lat", "Long"), names_to = "date", values_to = "cases") %>%
  select(-c(Lat, Long))
global_cases
```

```{r}
# pivot global deaths
global_deaths <- global_deaths %>%
  pivot_longer(cols = -c("Province/State", "Country/Region", "Lat", "Long"), names_to = "date", values_to = "deaths") %>%
  select(-c(Lat, Long))
global_deaths
```

# combine cases and deaths, rename columns, convert dates

```{r}
us <- us_cases %>%
  full_join(us_deaths) %>%
  rename("City" = "Admin2") %>%
  mutate(date = mdy(date)) %>%
  select("City", "Province_State", "Country_Region", "date", "cases", "deaths", "Population", "Combined_Key")
us
```

```{r}
global <- global_cases %>%
  full_join(global_deaths) %>%
  rename("Province_State" = "Province/State", "Country_Region" = "Country/Region") %>%
  mutate(date = mdy(date))
global
```

# Summary Data

```{r}
summary(us)
```

```{r}
summary(global)
```

# Filter Data

```{r}
us <- us %>% dplyr::filter(cases > 0)
summary(us)
```

```{r}
global <- global %>% dplyr::filter(cases > 0)
summary(global)
```

# Create Combined Key

```{r}
global <- global %>%
  unite("Combined_Key", c("Province_State", "Country_Region"), sep = ", ", na.rm = TRUE, remove = FALSE)
global
```

# Fetch Population

```{r}
url <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/UID_ISO_FIPS_LookUp_Table.csv"
uid <- read_csv(url) %>%
  select(-c(Lat, Long_, Combined_Key, code3, iso2, iso3, Admin2))
uid
```

```{r}
global <- global %>%
  left_join(uid, by = c("Province_State", "Country_Region")) %>%
  select(-c("UID", "FIPS")) %>%
  select("Province_State", "Country_Region", "date", "cases", "deaths", "Population", "Combined_Key")
global
```

# visualize data

```{r}
us_by_state <- us %>%
  group_by(Province_State, Country_Region, date) %>%
  summarize(cases = sum(cases), deaths = sum(deaths), Population = sum(Population)) %>%
  mutate(cases_per_million = cases * 1000000 / Population, deaths_per_million = deaths * 1000000 / Population) %>%
  select(Province_State, Country_Region, date, cases, deaths, cases_per_million, deaths_per_million, Population) %>%
  ungroup()
us_by_state
```

```{r}
us_totals <- us_by_state %>%
  group_by(Country_Region, date) %>%
  summarize(cases = sum(cases), deaths = sum(deaths), Population = sum(Population)) %>%
  mutate(cases_per_million = cases * 1000000 / Population, deaths_per_million = deaths * 1000000 / Population) %>%
  select(Country_Region, date, cases, deaths, cases_per_million, deaths_per_million, Population) %>%
  ungroup()
us_totals
```

```{r}
us_totals %>%
  dplyr::filter(cases > 0) %>%
  ggplot(aes(x = date, y = cases)) +
  geom_line(aes(color = "cases")) +
  geom_point(aes(color = "cases")) +
  geom_line(aes(y = deaths, color = "deaths")) +
  geom_point(aes(y = deaths, color = "deaths")) +
  scale_y_log10() +
  theme(legend.position = "bottom", axis.text.x = element_text(angle = 90)) +
  labs(title = "COVID19 in US", y = NULL)
```

```{r}
state <- "Tennessee"
us_by_state %>%
  dplyr::filter(Province_State == state) %>%
  dplyr::filter(cases > 0) %>%
  ggplot(aes(x = date, y = cases)) +
  geom_line(aes(color = "cases")) +
  geom_point(aes(color = "cases")) +
  geom_line(aes(y = deaths, color = "deaths")) +
  geom_point(aes(y = deaths, color = "deaths")) +
  scale_y_log10() +
  theme(legend.position = "bottom", axis.text.x = element_text(angle = 90)) +
  labs(title = str_c("COVID19 in ", state), y = NULL)
```

```{r}
max(us_totals$date)
max(us_totals$cases)
max(us_totals$deaths)
```

# Analyze Data

```{r}
us <- us %>%
  mutate(new_cases = cases - dplyr::lag(cases), new_deaths = deaths - dplyr::lag(deaths))
us_by_state <- us_by_state %>%
  mutate(new_cases = cases - dplyr::lag(cases), new_deaths = deaths - dplyr::lag(deaths))
us_totals <- us_totals %>%
  mutate(new_cases = cases - dplyr::lag(cases), new_deaths = deaths - dplyr::lag(deaths))
```

```{r}
us
```

```{r}
us_by_state
```

```{r}
us_totals
```

```{r}
us_totals %>%
  ggplot(aes(x = date, y = new_cases)) +
  geom_line(aes(color = "new_cases")) +
  geom_point(aes(color = "new_cases")) +
  geom_line(aes(y = new_deaths, color = "new_deaths")) +
  geom_point(aes(y = new_deaths, color = "new_deaths")) +
  scale_y_log10() +
  theme(legend.position = "bottom", axis.text.x = element_text(angle = 90)) +
  labs(title = "COVID19 in US", y = NULL)
```

```{r}
state <- "Tennessee"
us_by_state %>%
  filter(Province_State == state) %>%
  ggplot(aes(x = date, y = new_cases)) +
  geom_line(aes(color = "new_cases")) +
  geom_point(aes(color = "new_cases")) +
  geom_line(aes(y = new_deaths, color = "new_deaths")) +
  geom_point(aes(y = new_deaths, color = "new_deaths")) +
  scale_y_log10() +
  theme(legend.position = "bottom", axis.text.x = element_text(angle = 90)) +
  labs(title = str_c("COVID19 in", state), y = NULL)
```

```{r}
us_state_totals <- us_by_state %>%
  group_by(Province_State) %>%
  summarize(cases = max(cases), deaths = max(deaths), Population = max(Population), cases_per_thousand = 1000 * cases / Population, deaths_per_thousand = 1000 * deaths / Population) %>%
  dplyr::filter(cases > 0, Population > 0) %>%
  ungroup()
```

```{r}
us_state_totals %>%
  slice_min(deaths_per_thousand, n = 10)
```

```{r}
us_state_totals %>%
  slice_min(deaths_per_thousand, n = 10) %>%
  select(deaths_per_thousand, cases_per_thousand, everything())
```

```{r}
us_state_totals %>%
  slice_max(deaths_per_thousand, n = 10)
```

```{r}
us_state_totals %>%
  slice_max(deaths_per_thousand, n = 10) %>%
  select(deaths_per_thousand, cases_per_thousand, everything())
```

# Model Data

```{r}
model <- lm(deaths_per_thousand ~ cases_per_thousand, data = us_state_totals)
summary(model)
```

```{r}
us_state_totals %>% mutate(pred = predict(model))
```


```{r}
us_totals_w_pred <- us_state_totals %>% mutate(pred = predict(model))
us_totals_w_pred
```

```{r}
us_totals_w_pred %>% ggplot() +
  geom_point(aes(x = cases_per_thousand, y = deaths_per_thousand), color = "blue") +
  geom_point(aes(x = cases_per_thousand, y = pred), color = "red")
```



































































